name: TerrificTransmutation
version: 1.0
api-version: 1.15
author: BoBoBalloon
main: plugins.BoBoBalloon.TerrificTransmutation.TerrificTransmutation
description: Transmutation in minecraft!

commands:
  gettome:
    description: get an transmutation tome
    permission: terrifictransmutation.command.gettome
  terrifictransmutation:
    description: default command
permissions:
  terrifictransmutation.*:
   description: All access permission
   default: op
   children:
      terrifictransmutation.usetome: true
      terrifictransmutation.command.*: true
  terrifictransmutation.usetome:
   description: Allows player to use a transmutation tome
   default: op
  terrifictransmutation.command.*:
   description: All command access permission
   default: op
   children:
      terrifictransmutation.command.gettome: true
  terrifictransmutation.command.gettome:
   description: Allows gettome command
   default: op